### ISSUE TITLE
Raspberry pi CPU temp

### ISSUE THREAD

**Issue by vzorglub** [eschava/psmqtt#9]
Hello,
I get an error:
`Exception: Element 'sensors_temperatures' in 'sensors_temperatures/*' is not supported`
When using psmqtt on a rapsberry pi zero
Has the CPU temperature been implemented for raspis yet?

**Comment by eschava** [comment]
Sorry,  could you please provide more info?
What type of request do you use? Is it scheduled request or request via request/* topic?

**Comment by vzorglub** [comment]
I use a scheduled request:
```
import socket

mqtt_broker = 'localhost'       # default: 'localhost'
mqtt_port = 1883                # default: 1883
mqtt_clientid = 'psmqtt-1'
mqtt_username = 'username'
mqtt_password = 'password'
mqtt_clean_session = False
mqtt_qos = 0
mqtt_retain = False
mqtt_topic_prefix = 'psmqtt/pizero/'
#mqtt_topic_prefix = 'psmqtt/' + socket.gethostname() + '/'
mqtt_request_topic = 'request'

schedule = {
    "every 1 minute" :    [
        "cpu_percent",
        "virtual_memory/percent",
        "boot_time",
        "sensors_temperatures/*",
     ],
    "every 60 minutes"  :     "disk_usage/percent/|",  # slash replaced with ve$
    "every 3 hours" : {
        "boot_time/{{x|uptime}}": "uptime",
    }
}
```

**Comment by eschava** [comment]
I see. Could you please ensure that you use the latest version of psmqtt?
I've checked your configuration and it works OK at my box

**Comment by vzorglub** [comment]
Do I just replace the psmqtt.py file with the new one?

**Comment by vzorglub** [comment]
Nope, not working
I'll do a fresh install from rasbian image anyway in a few days time and let you know how it goes
Thanks

**Comment by vzorglub** [comment]
Nope,
Fresh raspbian install
I am using a pizero

**Comment by eschava** [comment]
same error?

**Comment by vzorglub** [comment]
No,  no errors, but no message...

**Comment by eschava** [comment]
How do you check the output?

You can try
`mosquitto_sub -t psmqtt/#`
command to see all messages sent by psqmtt

Also I've committed minor change that should improve messages sent for sensor_temparatures request

**Comment by vzorglub** [comment]
I use node-red mqtt node subscribed on #
I get the other 3 messages from the pi

**Comment by vzorglub** [comment]
Still the same,
I have changed handlers.py with your latest code but no luck.

**Comment by vzorglub** [comment]
Ok, I have done a bit of research and it appears that the psutil library doesn't work for sensors_temperature on raspberry pis:

[https://github.com/giampaolo/psutil/issues/1310](url)

**Comment by vzorglub** [comment]
The original issue was closed.
Maybe you have more influence in getting it reopened

**Comment by eschava** [comment]
It's reopened without my influence :)

**Comment by vzorglub** [comment]
That's great. Millions of raspberry pis out there...

**Comment by osos** [comment]
There is a specieal command to view rasperry pi temperature. Some info here: https://pimylifeup.com/raspberry-pi-temperature/

Running in bash:
```
$ /opt/vc/bin/vcgencmd measure_temp
temp=42.0'C

```
Maybe psmqtt could call that process on raspberry pies
